--COLOCAMOS ENTRE COLCHETES PARA POSSIBILITAR A NOMEAÇÃO COM ESPAÇOS
CREATE DATABASE [VENDAS SUCOS];

CREATE DATABASE [VENDAS SUCOS 2]
ON (
NAME='VENDAS_SUCOS_2_DAT', --NOME LOGICO
FILENAME='C:\TEMP\VENDAS_SUCOS_02.MDF',--ARQUIVO FISICO
SIZE=10, --TAMANHO INICIAL
MAXSIZE=50, --TAMANHO MAXIMO
FILEGROWTH=5 --VAI CRESCER DE 5 EM 5MB
)
--PARA LOG, CRIAMOS LOG ON
LOG ON (
NAME='VENDAS_SUCOS_2_LOG', --NOME LOGICO
FILENAME='C:\TEMP\VENDAS_SUCOS_02.LDF',--ARQUIVO FISICO
SIZE=10, --TAMANHO INICIAL
MAXSIZE=50, --TAMANHO MAXIMO
FILEGROWTH=5 --VAI CRESCER DE 5 EM 5MB
)


