SELECT
	TAMANHO
FROM
	TABELA_DE_PRODUTOS;

SELECT
	CAST(SUBSTRING(TAMANHO, 1, CHARINDEX(' ', TAMANHO, 1)) AS FLOAT)
FROM
	TABELA_DE_PRODUTOS;

SELECT
    CAST(SUBSTRING(TAMANHO, 1, CASE WHEN CHARINDEX(' ', TAMANHO) > 0 THEN CHARINDEX(' ', TAMANHO) - 1 ELSE LEN(TAMANHO) END) AS FLOAT)
FROM
    TABELA_DE_PRODUTOS;

SELECT
TC.NOME,
DATA_VENDA,
QUANTIDADE,
   CASE
		WHEN  
			CAST(
			SUBSTRING(
				REPLACE(TAMANHO, ' ', ''),
				1, 
				PATINDEX('%[^0-9]%', 
				REPLACE(TAMANHO, ' ', '')) - 1
			) AS FLOAT) > 2
		THEN 
		( CAST(
		SUBSTRING(
			REPLACE(TAMANHO, ' ', ''),
			1, 
			PATINDEX('%[^0-9]%', 
			REPLACE(TAMANHO, ' ', '')) - 1
		) AS FLOAT))/1000
		ELSE
			 CAST(
		SUBSTRING(
			REPLACE(TAMANHO, ' ', ''),
			1, 
			PATINDEX('%[^0-9]%', 
			REPLACE(TAMANHO, ' ', '')) - 1
		) AS FLOAT)
		END LITRO_PRODUTO
FROM
    TABELA_DE_PRODUTOS TP
INNER JOIN
	ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN
	NOTAS_FISCAIS NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN
	TABELA_DE_CLIENTES TC
ON NF.CPF = TC.CPF

SELECT *, L.QUANTIDADE*L.LITRO_PRODUTO LITRO_COMPRA 
FROM (SELECT
TC.NOME,
DATA_VENDA,
QUANTIDADE,
   CASE
		WHEN  
			CAST(
			SUBSTRING(
				REPLACE(TAMANHO, ' ', ''),
				1, 
				PATINDEX('%[^0-9]%', 
				REPLACE(TAMANHO, ' ', '')) - 1
			) AS FLOAT) > 2
		THEN 
		( CAST(
		SUBSTRING(
			REPLACE(TAMANHO, ' ', ''),
			1, 
			PATINDEX('%[^0-9]%', 
			REPLACE(TAMANHO, ' ', '')) - 1
		) AS FLOAT))/1000
		ELSE
			 CAST(
		SUBSTRING(
			REPLACE(TAMANHO, ' ', ''),
			1, 
			PATINDEX('%[^0-9]%', 
			REPLACE(TAMANHO, ' ', '')) - 1
		) AS FLOAT)
		END LITRO_PRODUTO
FROM
    TABELA_DE_PRODUTOS TP
INNER JOIN
	ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN
	NOTAS_FISCAIS NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN
	TABELA_DE_CLIENTES TC
ON NF.CPF = TC.CPF) L
GROUP BY MONTH(DATA_VENDA)



SELECT 
	NOME,
	MONTH(L.DATA_VENDA) MES,
	YEAR(L.DATA_VENDA) ANO,
	VOLUME_DE_COMPRA VOLUME_CLIENTE,
	SUM(L.QUANTIDADE * L.LITRO_PRODUTO) AS LITRO_COMPRA,
	CASE
		WHEN SUM(L.QUANTIDADE * L.LITRO_PRODUTO) <= VOLUME_DE_COMPRA 
		THEN 'APROVADO'
		ELSE 'EXCEDEU'
	END LIMITE_VOLUME
FROM (
    SELECT
        TC.NOME,
        DATA_VENDA,
        QUANTIDADE,
        CASE
            WHEN CAST(SUBSTRING(REPLACE(TAMANHO, ' ', ''), 1, PATINDEX('%[^0-9]%', REPLACE(TAMANHO, ' ', '')) - 1) AS FLOAT) > 2
            THEN (CAST(SUBSTRING(REPLACE(TAMANHO, ' ', ''), 1, PATINDEX('%[^0-9]%', REPLACE(TAMANHO, ' ', '')) - 1) AS FLOAT)) / 1000
            ELSE CAST(SUBSTRING(REPLACE(TAMANHO, ' ', ''), 1, PATINDEX('%[^0-9]%', REPLACE(TAMANHO, ' ', '')) - 1) AS FLOAT)
        END AS LITRO_PRODUTO,
		TC.VOLUME_DE_COMPRA
    FROM
        TABELA_DE_PRODUTOS TP
    INNER JOIN
        ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN
        NOTAS_FISCAIS NF ON INF.NUMERO = NF.NUMERO
    INNER JOIN
        TABELA_DE_CLIENTES TC ON NF.CPF = TC.CPF
) L

GROUP BY NOME, MONTH(L.DATA_VENDA), YEAR(L.DATA_VENDA), VOLUME_DE_COMPRA
ORDER BY ANO, MES, NOME




-------------------------------------------------------------------------------


SELECT
	NOME,
	MES,
	ANO,
	VOLUME_CLIENTE,
	LITRO_COMPRA,
	CASE
		WHEN LIMITE_VOLUME = 'EXCEDEU' 
		THEN CONCAT(VRF.LIMITE_VOLUME, 
		' em ', VRF.LITRO_COMPRA-VRF.VOLUME_CLIENTE, ' litros.')
		ELSE LIMITE_VOLUME
		END STATUS
FROM (SELECT 
	NOME,
	MONTH(L.DATA_VENDA) MES,
	YEAR(L.DATA_VENDA) ANO,
	VOLUME_DE_COMPRA VOLUME_CLIENTE,
	SUM(L.QUANTIDADE * L.LITRO_PRODUTO) AS LITRO_COMPRA,
	CASE
		WHEN SUM(L.QUANTIDADE * L.LITRO_PRODUTO) <= VOLUME_DE_COMPRA 
		THEN 'APROVADO'
		ELSE 'EXCEDEU'
	END LIMITE_VOLUME
FROM (
    SELECT
        TC.NOME,
        DATA_VENDA,
        QUANTIDADE,
        CASE
            WHEN CAST(SUBSTRING(REPLACE(TAMANHO, ' ', ''), 
			1, PATINDEX('%[^0-9]%', REPLACE(TAMANHO, ' ', '')) - 1) AS FLOAT) > 2
            THEN (CAST(SUBSTRING(REPLACE(TAMANHO, ' ', ''), 
			1, PATINDEX('%[^0-9]%', REPLACE(TAMANHO, ' ', '')) - 1) AS FLOAT)) / 1000
            ELSE CAST(SUBSTRING(REPLACE(TAMANHO, ' ', ''), 
			1, PATINDEX('%[^0-9]%', REPLACE(TAMANHO, ' ', '')) - 1) AS FLOAT)
        END AS LITRO_PRODUTO,
		TC.VOLUME_DE_COMPRA
    FROM
        TABELA_DE_PRODUTOS TP
    INNER JOIN
        ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN
        NOTAS_FISCAIS NF ON INF.NUMERO = NF.NUMERO
    INNER JOIN
        TABELA_DE_CLIENTES TC ON NF.CPF = TC.CPF
) L

GROUP BY NOME, MONTH(L.DATA_VENDA), YEAR(L.DATA_VENDA), VOLUME_DE_COMPRA) VRF


-----------------------------------------------------------