SELECT
	NF.CPF,
	NF.DATA_VENDA,
	INF.QUANTIDADE
FROM NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO= INF.NUMERO


SELECT
	NF.CPF,
	CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS MES_ANO,
	SUM(INF.QUANTIDADE) QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO= INF.NUMERO
GROUP BY 
NF.CPF,	CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
ORDER BY CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)



SELECT 
TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO, TV.QUANTIDADE_TOTAL
FROM TABELA_DE_CLIENTES TC
INNER JOIN
(SELECT
	NF.CPF,
	CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS MES_ANO,
	SUM(INF.QUANTIDADE) QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO= INF.NUMERO
GROUP BY 
NF.CPF,	CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)) TV
ON TC.CPF = TV.CPF





SELECT 
TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO, TV.QUANTIDADE_TOTAL,
(CASE WHEN TC.VOLUME_DE_COMPRA <= TV.QUANTIDADE_TOTAL THEN 'INVÁLIDO'
ELSE 'VÁLIDO' END) RESULTADO
FROM TABELA_DE_CLIENTES TC
INNER JOIN
(SELECT
	NF.CPF,
	CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS MES_ANO,
	SUM(INF.QUANTIDADE) QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO= INF.NUMERO
GROUP BY 
NF.CPF,	CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)) TV
ON TC.CPF = TV.CPF
WHERE TV.MES_ANO = '2015-01'


