SELECT DATEADD(DAY,28000,GETDATE())

SELECT DATEDIFF(HOUR,DATEADD(DAY,28000,GETDATE()), '1999-08-31')

SELECT GETDATE();

SELECT DAY('1999-08-31') DIA;
SELECT MONTH('1999-08-31') MES;
SELECT YEAR('1999-08-31') ANO;

SELECT DATETIMEFROMPARTS(2024,03,31,0,0,0,0)

---------------------------------

SELECT DATEADD(DAY, 10, GETDATE()) DATA_DAQUI_10_DIAS

SELECT DATEADD(DAY, -48, GETDATE()) DATA_48_DIAS_ATRAS


SELECT GETDATE() DIA_DE_HOJE, 
DATEADD(DAY, 10, GETDATE()) DATA_DAQUI_10_DIAS,
DATEADD(DAY, -48, GETDATE()) DATA_48_DIAS_ATRAS,
DATEDIFF(DAY,'2024-01-01',DIA_DE_) DIA_DESDE_INICIO_ANO


SELECT
	DATEDIFF(YEAR, DATA_DE_NASCIMENTO, GETDATE())
FROM
	TABELA_DE_CLIENTES
ORDER BY
	DATA_DE_NASCIMENTO DESC;

SELECT 
	DATEDIFF(YEAR, DATA_DE_NASCIMENTO, GETDATE()),
	(CAST((DATEDIFF(MONTH, DATA_DE_NASCIMENTO, GETDATE()) AS decimal)%
	(CAST(GETDATE() AS DECIMAL),
	DATEDIFF(DAY, DATA_DE_NASCIMENTO, GETDATE())
FROM
	TABELA_DE_CLIENTES
ORDER BY
	DATA_DE_NASCIMENTO DESC;

SELECT
	GETDATE(),
	DATA_DE_NASCIMENTO,
    DATEDIFF(YEAR, DATA_DE_NASCIMENTO, GETDATE()) AS IdadeAnos,
    DATEDIFF(MONTH, DATA_DE_NASCIMENTO, GETDATE()) % 12 AS IdadeMeses,
    DATEDIFF(DAY, DATA_DE_NASCIMENTO, GETDATE()) % 365 AS IdadeDias
FROM 
    TABELA_DE_CLIENTES
ORDER BY 
    DATA_DE_NASCIMENTO DESC;

	--------------------------------------------------
/*
Como seria a consulta que retornasse o nome do cliente
e sua data de nascimento por extenso dia, dia da semana, mês e ano?

Dica: Mais uma função de data que você deve pesquisar na
documentação. Chama-se DATENAME. 
Use ela concatenando com o nome do cliente.

*/
SELECT
	SUBSTRING(NOME, 1, CHARINDEX(' ', NOME)) 
	+ ', borned on ' 
	+ DATENAME(WEEKDAY, DATA_DE_NASCIMENTO)
	+ ' '
	+ DATENAME(MONTH,DATA_DE_NASCIMENTO)
	+ ' '
	+ DATENAME(DAY,DATA_DE_NASCIMENTO)
	+ 
		CASE
			WHEN DAY(DATA_DE_NASCIMENTO) IN (1, 21, 31)
				THEN + 'st, '
			WHEN DAY(DATA_DE_NASCIMENTO) IN (2, 22)
				THEN + 'nd, '
			WHEN DAY(DATA_DE_NASCIMENTO) IN (3, 23)
				THEN + 'rd, '
			ELSE + 'th, '
		END
	+ DATENAME(YEAR, DATA_DE_NASCIMENTO) AS SENTENCA
FROM
	TABELA_DE_CLIENTES

-- RESPOSTA DA ALURA
SELECT NOME + ' nasceu em ' + 
DATENAME (WEEKDAY,DATA_DE_NASCIMENTO) + ', ' +
DATENAME (DAY,DATA_DE_NASCIMENTO) + ' de ' +
DATENAME(MONTH, DATA_DE_NASCIMENTO) + ' de ' +
DATENAME(YEAR, DATA_DE_NASCIMENTO) AS DATA_EXTENSO
FROM TABELA_DE_CLIENTES;