SELECT PI();

SELECT
	PI() PI,
	ROUND(PI(),2) ROUND,
	CEILING(PI()) CEILING,
	FLOOR (PI()) FLOOR,
	POWER (PI(), PI()) PI_POWERED_PI,
	EXP (1) EXPONENCIAL,
	EXP (PI()) EXP_PI,
	SQRT(PI()) SQUARE_ROOT,
	PI()*-1 NEGATIVE,
	ABS (PI()*-1) ABSOLUTE;
------------------------------------------

SELECT * FROM NOTAS_FISCAIS;
SELECT * FROM ITENS_NOTAS_FISCAIS;

CREATE VIEW IMPOSTO_2016 AS

SELECT
	INF.CODIGO_DO_PRODUTO,
	TP.NOME_DO_PRODUTO,
	NF.DATA_VENDA,
	INF.QUANTIDADE,
	INF.PRECO,
	(INF.PRECO) * (INF.QUANTIDADE) AS VALOR_TOTAL,
	NF.IMPOSTO,
	ROUND((NF.IMPOSTO) * ((INF.PRECO) * (INF.QUANTIDADE)), 2) IMPOSTO_TOTAL
FROM
	TABELA_DE_PRODUTOS TP
INNER JOIN
	ITENS_NOTAS_FISCAIS INF
ON
	TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN
	NOTAS_FISCAIS NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016

--VIEW CRIADA
SELECT
	ROUND(SUM(IMPOSTO_TOTAL), 2),
	ROUND(SUM(VALOR_TOTAL), 2)
FROM
	IMPOSTO_2016;

--ALTER VIEW
ALTER VIEW IMPOSTO_2016 AS

SELECT
	INF.CODIGO_DO_PRODUTO,
	TP.NOME_DO_PRODUTO,
	NF.DATA_VENDA,
	INF.QUANTIDADE,
	INF.PRECO,
	(INF.PRECO) * (INF.QUANTIDADE) AS VALOR_TOTAL_PRODUTO,
	NF.IMPOSTO,
	ROUND((NF.IMPOSTO) * ((INF.PRECO) * (INF.QUANTIDADE)), 2) IMPOSTO_TOTAL_PRODUTO
FROM
	TABELA_DE_PRODUTOS TP
INNER JOIN
	ITENS_NOTAS_FISCAIS INF
ON
	TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN
	NOTAS_FISCAIS NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016

--
SELECT
	ROUND(SUM(IMPOSTO_TOTAL_PRODUTO), 2) IMPOSTO_TOTAL,
	ROUND(SUM(VALOR_TOTAL_PRODUTO), 2) VALOR_TOTAL
FROM
	IMPOSTO_2016;

--RESOULCAO ALURA
SELECT
	YEAR(DATA_VENDA) AS ANO,
	FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) IMPOSTO_TOTAL 
FROM
	NOTAS_FISCAIS NF
INNER JOIN
	ITENS_NOTAS_FISCAIS INF
ON
	NF.NUMERO = INF.NUMERO
WHERE
	YEAR(DATA_VENDA) = 2016
GROUP BY
	YEAR(DATA_VENDA);