--DATA PRA TEXTO É UMA DAS CONVERSÕES MAIS UTILIZADAS
SELECT CONVERT(VARCHAR(10), GETDATE(), 121);
--DEU ERRADO POIS O VARCHAR É DE 10

SELECT CONVERT(VARCHAR(25), GETDATE(), 121);

SELECT * FROM TABELA_DE_CLIENTES

SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(25), DATA_DE_NASCIMENTO, 106)
FROM TABELA_DE_CLIENTES;

SELECT 
	NOME_DO_PRODUTO,
	PRECO_DE_LISTA
FROM
	TABELA_DE_PRODUTOS

--FLOAT PARA TEXTO É IMPLICITO
SELECT 
	NOME_DO_PRODUTO,
	CONCAT('O preço do produto é de R$ ', 
	ROUND(PRECO_DE_LISTA,2), '.')
FROM
	TABELA_DE_PRODUTOS

--MAS SE DER ALGUM PROBLEMA, USE O CAST
SELECT 
	NOME_DO_PRODUTO,
	CONCAT('O preço do produto é de R$ ', 
	ROUND(CAST(PRECO_DE_LISTA AS VARCHAR(10)), 2), '.')
FROM
	TABELA_DE_PRODUTOS

--------------------------------------------------------
--ATIVIDADE
/*
Queremos construir um SQL cujo resultado seja para cada cliente:

    "O cliente João da Silva comprou R$ 121222,12 no ano de 2016".

Faça isso somente para o ano de 2016.
*/

SELECT
	CONCAT('O cliente ', TRIM(TC.NOME), ' comprou R$',
	STR(SUM(INF.PRECO*INF.QUANTIDADE), 10, 2),
	' no ano de ', YEAR(DATA_VENDA), '.') AS VALOR --O ''.'' E 'AS VALOR' NAO TINHA COLOCADO
FROM NOTAS_FISCAIS NF
INNER JOIN TABELA_DE_CLIENTES TC
ON NF.CPF = TC.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA), TC.NOME;

--ALURA

SELECT 
	TC.NOME, CONCAT('O cliente ', TC.NOME, ' comprou R$ ',
	TRIM(STR(SUM(IT.QUANTIDADE * IT.PRECO) ,10,2)), 
	' no ano de ', YEAR(NF.DATA_VENDA), '.') AS VALOR
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS IT ON NF.NUMERO = IT.NUMERO
INNER JOIN TABELA_DE_CLIENTES AS TC ON NF.CPF = TC.CPF
WHERE YEAR(NF.DATA_VENDA) = '2016'
GROUP BY TC.NOME, YEAR(NF.DATA_VENDA);


--VERSÃO MELHORADA (COM O TEXTO DE ACORDO COM O CLIENTE: HOMEM OU MULHER)

SELECT
	CONCAT(
	CASE 
	WHEN SUBSTRING(NOME, 1, CHARINDEX(' ', NOME, 1)) LIKE '%a' THEN 'A cliente '
	WHEN SUBSTRING(NOME, 1, CHARINDEX(' ', NOME, 1)) IN ('Átila', 'Joshua','Nicola','Noa','Djalma','Akira') THEN 'O cliente'
	ELSE 'O cliente '
	END, TRIM(TC.NOME), ' comprou R$ ',
	STR(SUM(INF.PRECO*INF.QUANTIDADE), 10, 2),
	' no ano de ', YEAR(DATA_VENDA))
FROM NOTAS_FISCAIS NF
INNER JOIN TABELA_DE_CLIENTES TC
ON NF.CPF = TC.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA), TC.NOME


--PENSANDO MELHOR... É MELHOR USAR O GÊNERO DO CLIENTE
SELECT
	CONCAT(
	CASE 
	WHEN TC.GENERO = 'F' THEN 'A cliente '
	ELSE 'O cliente '
	END, TRIM(TC.NOME), ' comprou R$ ',
	STR(SUM(INF.PRECO*INF.QUANTIDADE), 10, 2),
	' no ano de ', YEAR(DATA_VENDA))
FROM NOTAS_FISCAIS NF
INNER JOIN TABELA_DE_CLIENTES TC
ON NF.CPF = TC.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA), TC.NOME, TC.GENERO
ORDER BY TC.NOME


