SELECT
--INF.CODIGO_DO_PRODUTO,
--NF.NUMERO,
TC.NOME,
INF.QUANTIDADE,
TP.TAMANHO,
NF.DATA_VENDA

FROM TABELA_DE_CLIENTES TC
INNER JOIN
NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_PRODUTOS TP
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO


SELECT 
    CASE
        WHEN CAST(SUBSTRING(TAMANHO, 1, CHARINDEX(' ',TAMANHO, 1)) AS INT) > 2
		THEN CAST(SUBSTRING(TAMANHO, 1, CHARINDEX(' ',TAMANHO, 1)) AS INT) / 1000
        ELSE TAMANHO
    END AS NOVO_T
FROM TABELA_DE_PRODUTOS


SELECT
	TC.NOME,
	L.CODIGO_DO_PRODUTO,
	--L.NOME_DO_PRODUTO,
	NF.DATA_VENDA,
	L.LITROS,
	INF.QUANTIDADE,
	L.LITROS*INF.QUANTIDADE AS TOTAL_LITROS,
	SUM(L.LITROS*INF.QUANTIDADE) AS SOMA_LITROS
FROM
	TABELA_LITROS L
INNER JOIN
	ITENS_NOTAS_FISCAIS  INF
ON
	INF.CODIGO_DO_PRODUTO = L.CODIGO_DO_PRODUTO
INNER JOIN
	NOTAS_FISCAIS NF
ON
	NF.NUMERO = INF.NUMERO
INNER JOIN
	TABELA_DE_CLIENTES TC
ON
	NF.CPF = TC.CPF
GROUP BY
	TC.NOME,	
	L.CODIGO_DO_PRODUTO,
	L.LITROS,
	NF.DATA_VENDA,
	INF.QUANTIDADE
	

/*
ALTER VIEW TABELA_LITROS AS 
SELECT CODIGO_DO_PRODUTO,
NOME_DO_PRODUTO,
    CASE
        WHEN ISNUMERIC(LEFT(TAMANHO, PATINDEX('%[^0-9]%', TAMANHO + 'X') - 1)) = 1
        THEN
            CASE
                WHEN CAST(LEFT(TAMANHO, PATINDEX('%[^0-9]%', TAMANHO + 'X') - 1) AS INT) > 2
                THEN 
                    CAST(LEFT(TAMANHO, PATINDEX('%[^0-9]%', TAMANHO + 'X') - 1) AS FLOAT) / 1000
                ELSE
                    CAST(LEFT(TAMANHO, PATINDEX('%[^0-9]%', TAMANHO + 'X') - 1) AS INT)
            END
        ELSE
            NULL
    END AS LITROS
FROM 
    TABELA_DE_PRODUTOS*/
SELECT * FROM LITROS;