SELECT * FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE > 20;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE < 20;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE <= 18;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE < 18;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE <> 18;

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= '1995-11-14';

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO < '1995-11-14';

SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO >= 'LAPA';

------------------------------------------------------------

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS WHERE 1=1;

SELECT * FROM TABELA_DE_PRODUTOS WHERE 1=0;

SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO = '290478';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'LARANJA';

SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'pet';

------------------------------------------------------------

SELECT COUNT(DISTINCT tp.Sabor) FROM TABELA_DE_PRODUTOS tp;

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS WHERE sabor='maca';

SELECT TOP 10 * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '2017-10-01';

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM, NOME_DO_PRODUTO;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM DESC, NOME_DO_PRODUTO DESC;

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;

SELECT TOP 1 * FROM ITENS_NOTAS_FISCAIS ORDER BY QUANTIDADE DESC;

SELECT CODIGO_DO_PRODUTO FROM TABELA_DE_PRODUTOS 
WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao';
--1101035

SELECT * FROM ITENS_NOTAS_FISCAIS 
WHERE CODIGO_DO_PRODUTO = 1101035
ORDER BY QUANTIDADE DESC;


SELECT CIDADE, AVG(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE;


SELECT CODIGO_DO_PRODUTO, COUNT(*) AS [QUANTIDADE DE NOTAS] FROM ITENS_NOTAS_FISCAIS 
WHERE CODIGO_DO_PRODUTO = 1013793 
GROUP BY CODIGO_DO_PRODUTO; --6971

SELECT COUNT(*) AS [QUANTIDADE DE NOTAS] FROM ITENS_NOTAS_FISCAIS 
WHERE CODIGO_DO_PRODUTO = 1101035 AND QUANTIDADE = 99


SELECT CODIGO_DO_PRODUTO, QUANTIDADE FROM ITENS_NOTAS_FISCAIS 
WHERE CODIGO_DO_PRODUTO = 1101035 AND QUANTIDADE = 99 --79 ROWS
