--CASE

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	  WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	  ELSE 'PRODUTO BARATO' END) AS CLASSIFICA플O
FROM TABELA_DE_PRODUTOS
ORDER BY CLASSIFICA플O;

SELECT (CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	  WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	  ELSE 'PRODUTO BARATO' END) AS CLASSIFICA플O, COUNT(*) NUMERO
FROM TABELA_DE_PRODUTOS
GROUP BY (CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	  WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	  ELSE 'PRODUTO BARATO' END)
ORDER BY CLASSIFICA플O;
---------------------------------------------------------------------
SELECT NOME, LIMITE_DE_CREDITO,
(CASE WHEN LIMITE_DE_CREDITO >=150000 THEN 'GRANDE'
	WHEN LIMITE_DE_CREDITO >=110000 AND LIMITE_DE_CREDITO < 150000 THEN 'MEDIOS'
	ELSE 'PEQUENO'
	END) TAMANHO_CLIENTE

FROM TABELA_DE_CLIENTES
ORDER BY LIMITE_DE_CREDITO DESC;

SELECT * FROM TABELA_DE_CLIENTES

SELECT NOME,
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'Clientes grandes'
WHEN LIMITE_DE_CREDITO < 150000 AND LIMITE_DE_CREDITO >= 110000 THEN 'Clientes medios'
ELSE 'Clientes pequenos' END) AS CLASSIFICACAO
FROM TABELA_DE_CLIENTES
ORDER BY CLASSIFICACAO
