SELECT TC.NOME, TC.CPF, TC.DATA_DE_NASCIMENTO,
COUNT(NUMERO) QUANTIDADE_DE_VENDAS
FROM TABELA_DE_CLIENTES TC
INNER JOIN
NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF
GROUP BY TC.NOME, TC.CPF, TC.DATA_DE_NASCIMENTO
ORDER BY QUANTIDADE_DE_VENDAS DESC;
