SELECT COUNT(*) FROM TABELA_DE_CLIENTES;

SELECT DISTINCT
TC.CPF, TC.NOME, NF.CPF 
FROM TABELA_DE_CLIENTES TC
LEFT JOIN NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF AND NF.CPF IS NULL
ORDER BY TC.NOME DESC;
