SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES;
--17 BAIRROS

SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
--4 BAIRROS

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
--18 BAIRROS

SELECT BAIRRO FROM TABELA_DE_CLIENTES
UNION
SELECT BAIRRO FROM TABELA_DE_VENDEDORES;
--18 BAIRROS

SELECT BAIRRO FROM TABELA_DE_CLIENTES
UNION ALL
SELECT BAIRRO FROM TABELA_DE_VENDEDORES;
--25 BAIRROS POIS TEM REPETIDOS

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
--21 BAIRROS

SELECT DISTINCT BAIRRO, 'CLIENTE' ORIGEM FROM TABELA_DE_CLIENTES
UNION 
SELECT DISTINCT BAIRRO, 'FORNECEDOR' ORIGEM FROM TABELA_DE_VENDEDORES;