/*
--CRIACAO DA VIEW
CREATE VIEW QUANTIDADE_PRODUTO AS
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO,
SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO*/

--ANTIGO
SELECT QUANTIDADE_PRODUTO.CODIGO_DO_PRODUTO,
QUANTIDADE_PRODUTO.NOME_DO_PRODUTO, QUANTIDADE_PRODUTO.QUANTIDADE
FROM
(SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO,
SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO) QUANTIDADE_PRODUTO
WHERE QUANTIDADE > 394000
ORDER BY QUANTIDADE DESC;

--NOVO
SELECT CODIGO_DO_PRODUTO,
NOME_DO_PRODUTO, QUANTIDADE
FROM QUANTIDADE_PRODUTO
WHERE QUANTIDADE > 394000
ORDER BY QUANTIDADE DESC;

--EXERCICIO



/*
Veja a consulta abaixo que foi resposta de um exercício anterior.
*/

SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, 
SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO 
HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

/*
Redesenhe esta consulta criando uma visão para a lista
de quantidades totais por produto e aplicando a condição 
e ordenação sobre esta mesma visão.
*/

--RESPOSTA:
/* 
--CRIACAO DA VIEW
CREATE VIEW TOTAL_POR_PRODUTO AS
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, 
SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO 
*/

SELECT * FROM TOTAL_POR_PRODUTO
WHERE QUANTIDADE > 394000 
ORDER BY QUANTIDADE DESC;

--TESTE
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, 
SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO 
HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;
