SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) PRECO_MEDIO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) PRECO_MEDIO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM
HAVING AVG(PRECO_DE_LISTA) <= 10;

SELECT MEDIA_EMBALAGEM.EMBALAGEM, 
MEDIA_EMBALAGEM.PRECO_MEDIO FROM (
SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) PRECO_MEDIO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM) MEDIA_EMBALAGEM
WHERE PRECO_MEDIO <= 10;
-----------------------------------------------------------
--EXERCICIO
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO,
SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO 
HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

--RESPOSTA
SELECT QUANTIDADE_PRODUTO.CODIGO_DO_PRODUTO,
QUANTIDADE_PRODUTO.NOME_DO_PRODUTO, QUANTIDADE_PRODUTO.QUANTIDADE
FROM
(SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO,
SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO) QUANTIDADE_PRODUTO
WHERE QUANTIDADE > 394000
ORDER BY QUANTIDADE DESC;